### ISSUE TITLE
Enable HTTPS for restify server

### ISSUE THREAD

**Issue by twhiteman** [bahamat/manta-shortener#4]
Enable HTTPS.

**Comment by bahamat** [comment]
I was planning to put it behind nginx and just have nginx so the TLS termination.

**Comment by twhiteman** [comment]
Sounds good to me.

**Comment by twhiteman** [comment]
Was https added? As I really meant for this issue to be "add https" :)

**Comment by bahamat** [comment]
Not yet, I need to operationalize the deployment, right now it's just kind of hacked up. I also want to redeploy to test out the new features (manta storage) before taking down the existing one.
