### ISSUE TITLE
Manta urls should be shard diverse

### ISSUE THREAD

**Issue by bahamat** [bahamat/manta-shortener#5]
The current path scheme looks like it’ll all land on the same shard.

E.G., current might be like this:

    /user/stor/shortener/0000000000

Where the base name is an object everything is in the same directory.

Instead, it should be like this:

    /user/stor/shortener/0000000000/link.json

This way the hash value becomes a directory name and the distribution will hopefully spread evenly across all shards.

**Comment by twhiteman** [comment]
A 3-character directory prefix is used (000-999) to split up the urls into different directories. So they should get spread across all shards this way.

Current manta paths will look like this:
```
/user/stor/shortener/000/0000000000
/user/stor/shortener/123/12345678901
```

**Comment by bahamat** [comment]
Perfect, that'll take are of this then.
